"""Generate the display-only catalog from the transcribed Roland waveform list."""
import argparse
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate():
    with (ROOT / "docs/data/xp60_internal_waves.csv").open(encoding="utf-8", newline="") as source:
        rows = list(csv.DictReader(source))
    expected = [(bank, n) for bank, size in (("INT-A", 255), ("INT-B", 193)) for n in range(1, size + 1)]
    if [(r["bank"], int(r["number"])) for r in rows] != expected:
        raise ValueError("Catalog must contain every INT-A and INT-B entry in source order")
    output = ["// Generated by tools/generate_wave_catalog.py; do not edit.",
              "// Display metadata only: bank labels do not establish SysEx group IDs.",
              "#pragma once", "#include <array>",
              "namespace xp60studio::presentation::catalog {",
              "struct Wave { const char* bank; int number; const char* name; int page; };",
              "inline constexpr std::array<Wave, 448> waves{{"]
    for row in rows:
        if not row["name"] or int(row["source_page"]) not in (1, 2, 3):
            raise ValueError("Missing waveform name or source page")
        output.append(f'    {{{json.dumps(row["bank"])}, {int(row["number"])}, {json.dumps(row["name"])}, {int(row["source_page"])}}},')
    return "\n".join(output + ["}};", "} // namespace xp60studio::presentation::catalog", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "src/presentation/Xp60WaveCatalog.generated.h"
    result = generate()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != result:
            raise SystemExit("Wave catalog is stale; run tools/generate_wave_catalog.py")
    else:
        target.write_text(result, encoding="utf-8", newline="\n")
