#!/usr/bin/env python3
"""Generate the SR-JV80 expansion waveform catalog from Roland's own lists.

Source of truth: docs/data/sr_jv80_expansion_waves.csv, transcribed from the
per-board Waveform List PDFs in docs/XP60-References/SR-JV80/. Those are
Roland's own documents, so a name here is Roland's name, not a reconstruction.

Only boards whose Waveform List this project actually holds appear. A board with
no list is absent rather than empty: "XP60Studio has no list for that board" and
"that board has no waves" are different statements, and the C++ side keeps them
apart.

Usage:
    tools/generate_expansion_waves.py            # rewrite the generated file
    tools/generate_expansion_waves.py --check    # exit 1 if it is stale
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/data/sr_jv80_expansion_waves.csv"
TARGET = ROOT / "src/library/generated/SrJv80WaveCatalog.generated.h"


def generate() -> str:
    with SOURCE.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError("Expansion wave catalog source is empty")

    boards: dict[int, list[str]] = {}
    for row in rows:
        board = int(row["board"])
        number = int(row["number"])
        name = row["name"]
        if not name:
            raise ValueError(f"Board {board} wave {number} has no name")
        entries = boards.setdefault(board, [])
        # Roland numbers waves from 1 and the list must be complete: a gap would
        # silently shift every later wave, which is the one error that would
        # make the catalog worse than having none.
        if number != len(entries) + 1:
            raise ValueError(f"Board {board} is not contiguous at wave {number}")
        entries.append(name)

    out = [
        "// Generated by tools/generate_expansion_waves.py; do not edit.",
        "//",
        "// Roland's own per-board Waveform Lists (docs/XP60-References/SR-JV80/).",
        "// `number` is the 1-based number Roland prints and the instrument displays;",
        "// a Tone's raw wave byte is one less, as hardware-verified for internal",
        "// waves in DEVICE_ACCEPTANCE.md area 9.",
        "#pragma once",
        "#include <array>",
        "#include <string_view>",
        "namespace xp60studio::library::srjv80 {",
        "struct BoardWaves { int board; std::string_view name; };",
        "",
    ]
    for board in sorted(boards):
        names = boards[board]
        out.append(f"inline constexpr std::array<std::string_view, {len(names)}> kBoard{board:02d}Waves{{{{")
        for name in names:
            out.append(f"    {json.dumps(name, ensure_ascii=False)},")
        out.append("}};")
        out.append("")

    out.append("struct BoardList { int board; const std::string_view* first; int count; };")
    out.append(f"inline constexpr std::array<BoardList, {len(boards)}> kBoardLists{{{{")
    for board in sorted(boards):
        out.append(
            f"    {{{board}, kBoard{board:02d}Waves.data(), {len(boards[board])}}},"
        )
    out.append("}};")
    out.append("} // namespace xp60studio::library::srjv80")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != result:
            raise SystemExit("Expansion wave catalog is stale; run tools/generate_expansion_waves.py")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(result, encoding="utf-8", newline="\n")
